### ISSUE TITLE
issues found on asdf-library(add more details later)

### ISSUE THREAD

**Issue by wjlei1990** [SeismicData/asdf-library#15]
### 1. rewrite issue

if already exists, it should first clean it out. But it seems not doing so.
### 2. stationxml issue

stationxml only reaches station level, not channel level
### 3. trace time issue

```
* trace starttime and endtime seems wrong
* trace delta and sampling rate wrong
```
### 4. quakeml file

```
 * header information wrong
 * event origin time calculation wrong
 * add more information in mb, Ms
```

**Comment by ghost** [comment]
Hi wjlei1990,

These issues are all fixed in the latest version of the SPECFEM3D_GLOBE writer for ASDF. It is available on my repository ( https://github.com/jas11/specfem3d_globe/tree/devel ) and will soon be available on the CIG respository.

Please continue giving feedback if you run into any problems.

Thanks,
James
